version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  app:
    build:
      context: .
    container_name: nodejs-blog-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/blog_app
    volumes:
      - .:/usr/src/app  # Mount the app directory inside the container

volumes:
  mongodb-data:
